# To run a container based on the image, allowing GUI access (unsecured way):
# xhost +
# docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -ti -e DISPLAY=$DISPLAY

FROM ubuntu:latest

# Timezone
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

# Install
RUN apt-get -y update && apt-get -y install \
  mesa-utils \
  vim \
  x11-utils

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

CMD ["/bin/bash"]
